### ISSUE TITLE
Changing events without closing the server

### ISSUE THREAD

**Issue by Evotushon** [ZeruLight/Erupe#16]
This is not a bug, just a request
I don't know if this can be done via pgAdmin, but it'd be a nice feature to have.

**Comment by Tsugami** [comment]
What '"events"?

**Comment by sekaiwish** [comment]
With how festa is currently implemented in its branch, you're able to adjust the starting timestamp and switch Lands to force some data to reload. You're able to skip to whatever stage of the event you're trying to test using this. Though this obviously doesn't apply to any other event yet.

**Comment by sekaiwish** [comment]
In hindsight this will not be supported as events will be designed to progress naturally alongside having debug options to force certain event stages to be active.
