### ISSUE TITLE
Unreachable code

### ISSUE THREAD

**Issue by EclipseKnight** [ZeruLight/Erupe#39]
https://github.com/ZeruLight/Erupe/blob/2ca72180763da10ce5ec7109adac480418b38989/server/channelserver/handlers_guild_alliance.go#L153

**Comment by Evotushon** [comment]
It is indeed unreachable, but there shouldn't be any unhandled operate joints as of right now

**Comment by sekaiwish** [comment]
This is definitely NOT unreachable. The only known Alliance/Joint opcode IDs are 1, 3 and 9. Every other opcode _may_ not exist in MHFZZ but _may_ exist in older versions. This code will not be removed for the case in the future where Erupe is forked to become an emulator for older versions where these opcodes _may_ exist.

**Comment by sekaiwish** [comment]
For future reference, these opcodes are defined here;
https://github.com/ZeruLight/Erupe/blob/main/network/mhfpacket/msg_mhf_operate_joint.go#L14-L16

**Comment by EclipseKnight** [comment]
@Tsugami is correct, the code is literally just unreachable because of the panic lol

**Comment by Evotushon** [comment]
> This is definitely NOT unreachable. The only known Alliance/Joint opcode IDs are 1, 3 and 9. Every other opcode _may_ not exist in MHFZZ but _may_ exist in older versions. This code will not be removed for the case in the future where Erupe is forked to become an emulator for older versions where these opcodes _may_ exist.

the thing is that the code panics before doing the ack simple succeed
