### ISSUE TITLE
unable to depart for quests

### ISSUE THREAD

**Issue by MrRedBread** [ZeruLight/Erupe#55]
everything seems to be working fine but whenever i depart for a quest i get these errors
![help fix it 1](https://user-images.githubusercontent.com/119906456/205785738-fefe8b34-67b7-418f-83f0-76ed9aad5939.JPG)
![help fix it 2](https://user-images.githubusercontent.com/119906456/205785748-b9d841e1-d4cd-4e11-be37-9cbcfd386e1f.JPG)
i can tell this is just a me problem i am not tech savvy at all so if theres a way to fix this would you be so kind to let me know in detail please

**Comment by ezemania2** [comment]
did you start sky coridor? because sky coridor is not available in ZZ

**Comment by MrRedBread** [comment]
> 

i have not departed for a quest that had the sky corridor map i seem get these errors whenever i depart for any map like the great forest, volcano, etc

**Comment by MrRedBread** [comment]
> did you start sky coridor? because sky coridor is not available in ZZ

i forgot to like quote your message idk if it counts as replying sorry if im being bothersome

**Comment by sekaiwish** [comment]
This is intended behavior as defined here:
https://github.com/ZeruLight/Erupe/blob/main/server/channelserver/handlers_quest.go#L56
