### ISSUE TITLE
A `failed get world infomation` error 

### ISSUE THREAD

**Issue by Psyke1004** [ZeruLight/Erupe#69]
**Description**:
A `failed get world infomation` error occurs when calling the world list after creating a character.
I would like to know what causes this error and how to fix it.

![Cap 2023-05-29 15-55-37-423](https://github.com/ZeruLight/Erupe/assets/20449064/b3417a6e-847a-4afe-ae40-26a318e2ed7a)

**Screenshots**

**Comment by Psyke1004** [comment]
Occurs when trying to access a channel in any situation.

**Comment by sasospanner** [comment]
did you recently update the server?

**Comment by Psyke1004** [comment]
I am using the latest server, and it runs well in the local environment. However, when I run the server in the virtual server, the following error occurs.

**Comment by sasospanner** [comment]
do you see any errors in the console of your virtual server whenever this error occurs?

**Comment by Psyke1004** [comment]
No, there are no error logs displayed on the virtual machine console.

![Cap 2023-06-03 07-49-28-790](https://github.com/ZeruLight/Erupe/assets/20449064/fd8e6d9b-64eb-445b-9496-e76974262d52)

**Comment by sasospanner** [comment]
Are you accessing the same database or 2 different ones?

**Comment by Linonrim** [comment]
Hello ! I have the same issue. Did you find any solution?

**Comment by Linonrim** [comment]
It works for me ! I just had to put my IP address in "host" instead of "localhost"

**Comment by CataclysmX** [comment]
To solve the problem, simply set the server's public IP in the "Host" field of the config. 🙂
